package busybee.billing.controller;

import busybee.billing.model.InvoiceRow;
import busybee.billing.model.PaymentRow;
import busybee.util.DateUtils;
import busybee.util.DialogUtils;
import busybee.util.NumberUtils;
import busybee.util.ValidationUtils;
import javafx.fxml.FXML;
import javafx.fxml.Initializable;
import javafx.scene.control.*;
import javafx.scene.layout.VBox;
import javafx.stage.Stage;

import java.net.URL;
import java.util.ResourceBundle;

public class BillingCreateController implements Initializable {

    @FXML private Label lblTitle;
    @FXML private VBox paymentFields, invoiceFields;
    @FXML private TextField txtRequestId, txtAmount, txtReceivedBy;
    @FXML private ComboBox<String> cbMethod;
    @FXML private TextField txtInvoiceRequestId, txtInvoiceNo, txtTotalAmount, txtGeneratedBy;
    @FXML private Button btnSearchRequest, btnSearchInvoiceRequest, btnSave, btnCancel;

    private PaymentRow payment;
    private InvoiceRow invoice;
    private boolean isPaymentMode = true;
    private boolean hasUnsavedChanges = false;

    @Override
    public void initialize(URL location, ResourceBundle resources) {
        setupValidation();
        setupButtons();
        setupChangeListeners();
    }

    public void setPayment(PaymentRow payment) {
        this.payment = payment;
        this.isPaymentMode = true;
        showPaymentFields();

        if (payment != null) {
            lblTitle.setText("Edit Payment - " + payment.getPaymentId());
            txtRequestId.setText(payment.getRequestId());
            txtAmount.setText(String.valueOf(payment.getAmount()));
            cbMethod.setValue(payment.getMethod());
            txtReceivedBy.setText(payment.getReceivedBy());
        } else {
            lblTitle.setText("Create Payment");
            generatePaymentId();
        }
    }

    public void setInvoice(InvoiceRow invoice) {
        this.invoice = invoice;
        this.isPaymentMode = false;
        showInvoiceFields();

        if (invoice != null) {
            lblTitle.setText("Edit Invoice - " + invoice.getInvoiceId());
            txtInvoiceRequestId.setText(invoice.getRequestId());
            txtInvoiceNo.setText(invoice.getInvoiceNo());
            txtTotalAmount.setText(String.valueOf(invoice.getTotalAmount()));
            txtGeneratedBy.setText(invoice.getGeneratedBy());
        } else {
            lblTitle.setText("Create Invoice");
            generateInvoiceId();
            generateInvoiceNo();
        }
    }

    private void showPaymentFields() {
        paymentFields.setVisible(true);
        invoiceFields.setVisible(false);
    }

    private void showInvoiceFields() {
        paymentFields.setVisible(false);
        invoiceFields.setVisible(true);
    }

    private void setupValidation() {
        // Amount validation
        txtAmount.textProperty().addListener((obs, oldText, newText) -> {
            if (!newText.matches("\\d*(\\.\\d{0,2})?")) {
                txtAmount.setText(oldText);
            }
        });

        txtTotalAmount.textProperty().addListener((obs, oldText, newText) -> {
            if (!newText.matches("\\d*(\\.\\d{0,2})?")) {
                txtTotalAmount.setText(oldText);
            }
        });
    }

    private void setupButtons() {
        btnSearchRequest.setOnAction(event -> searchRequest());
        btnSearchInvoiceRequest.setOnAction(event -> searchRequest());
        btnSave.setOnAction(event -> {
            if (isPaymentMode) {
                savePayment();
            } else {
                saveInvoice();
            }
        });
        btnCancel.setOnAction(event -> cancel());
    }

    private void setupChangeListeners() {
        // Mark as having unsaved changes when any field changes
        txtRequestId.textProperty().addListener((obs, old, newVal) -> hasUnsavedChanges = true);
        txtAmount.textProperty().addListener((obs, old, newVal) -> hasUnsavedChanges = true);
        cbMethod.valueProperty().addListener((obs, old, newVal) -> hasUnsavedChanges = true);
        txtReceivedBy.textProperty().addListener((obs, old, newVal) -> hasUnsavedChanges = true);
        txtInvoiceRequestId.textProperty().addListener((obs, old, newVal) -> hasUnsavedChanges = true);
        txtTotalAmount.textProperty().addListener((obs, old, newVal) -> hasUnsavedChanges = true);
        txtGeneratedBy.textProperty().addListener((obs, old, newVal) -> hasUnsavedChanges = true);
    }

    private void generatePaymentId() {
        // In a real app, this would be generated by the database
        // For demo, we'll use a simple counter
    }

    private void generateInvoiceId() {
        // In a real app, this would be generated by the database
    }

    private void generateInvoiceNo() {
        // Generate invoice number like INV-2024-001
        txtInvoiceNo.setText("INV-2024-" + String.format("%03d", (int)(Math.random() * 1000)));
    }

    private void searchRequest() {
        // In a real app, this would open a request search dialog
        DialogUtils.showInfo("Search Request", "Request search functionality would be implemented here.");
    }

    public void savePayment() {
        if (!validatePaymentFields()) {
            return;
        }

        try {
            if (payment == null) {
                payment = new PaymentRow();
                payment.setPaymentId("P" + String.format("%03d", (int)(Math.random() * 1000)));
                payment.setStatus("PAID");
                payment.setPaidAt(DateUtils.getCurrentDateTimeString());
            }

            payment.setRequestId(txtRequestId.getText());
            payment.setAmount(Double.parseDouble(txtAmount.getText()));
            payment.setMethod(cbMethod.getValue());
            payment.setReceivedBy(txtReceivedBy.getText());

            // In a real app, save to database here

            DialogUtils.showInfo("Success", "Payment saved successfully!");
            hasUnsavedChanges = false;
            closeWindow();

        } catch (Exception e) {
            DialogUtils.showError("Error", "Failed to save payment: " + e.getMessage());
        }
    }

    public void saveInvoice() {
        if (!validateInvoiceFields()) {
            return;
        }

        try {
            if (invoice == null) {
                invoice = new InvoiceRow();
                invoice.setInvoiceId("I" + String.format("%03d", (int)(Math.random() * 1000)));
                invoice.setStatus("ISSUED");
                invoice.setIssuedAt(DateUtils.getCurrentDateTimeString());
            }

            invoice.setRequestId(txtInvoiceRequestId.getText());
            invoice.setInvoiceNo(txtInvoiceNo.getText());
            invoice.setTotalAmount(Double.parseDouble(txtTotalAmount.getText()));
            invoice.setGeneratedBy(txtGeneratedBy.getText());

            // In a real app, save to database here

            DialogUtils.showInfo("Success", "Invoice saved successfully!");
            hasUnsavedChanges = false;
            closeWindow();

        } catch (Exception e) {
            DialogUtils.showError("Error", "Failed to save invoice: " + e.getMessage());
        }
    }

    private boolean validatePaymentFields() {
        if (txtRequestId.getText().trim().isEmpty()) {
            DialogUtils.showError("Validation Error", "Request ID is required.");
            return false;
        }

        if (txtAmount.getText().trim().isEmpty()) {
            DialogUtils.showError("Validation Error", "Amount is required.");
            return false;
        }

        try {
            double amount = Double.parseDouble(txtAmount.getText());
            if (!ValidationUtils.isPositive(amount)) {
                DialogUtils.showError("Validation Error", "Amount must be greater than 0.");
                return false;
            }
        } catch (NumberFormatException e) {
            DialogUtils.showError("Validation Error", "Invalid amount format.");
            return false;
        }

        if (cbMethod.getValue() == null) {
            DialogUtils.showError("Validation Error", "Payment method is required.");
            return false;
        }

        if (txtReceivedBy.getText().trim().isEmpty()) {
            DialogUtils.showError("Validation Error", "Received by is required.");
            return false;
        }

        return true;
    }

    private boolean validateInvoiceFields() {
        if (txtInvoiceRequestId.getText().trim().isEmpty()) {
            DialogUtils.showError("Validation Error", "Request ID is required.");
            return false;
        }

        if (txtTotalAmount.getText().trim().isEmpty()) {
            DialogUtils.showError("Validation Error", "Total amount is required.");
            return false;
        }

        try {
            double amount = Double.parseDouble(txtTotalAmount.getText());
            if (!ValidationUtils.isPositive(amount)) {
                DialogUtils.showError("Validation Error", "Total amount must be greater than 0.");
                return false;
            }
        } catch (NumberFormatException e) {
            DialogUtils.showError("Validation Error", "Invalid total amount format.");
            return false;
        }

        if (txtGeneratedBy.getText().trim().isEmpty()) {
            DialogUtils.showError("Validation Error", "Generated by is required.");
            return false;
        }

        return true;
    }

    private void cancel() {
        if (hasUnsavedChanges) {
            boolean confirm = DialogUtils.showConfirmation(
                "Unsaved Changes",
                "You have unsaved changes. Are you sure you want to cancel?"
            );
            if (!confirm) {
                return;
            }
        }
        closeWindow();
    }

    private void closeWindow() {
        Stage stage = (Stage) btnCancel.getScene().getWindow();
        stage.close();
    }

    public boolean hasUnsavedChanges() {
        return hasUnsavedChanges;
    }
}